import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
app_modbus_slave.c
modbus_event.c
pmc005.c
ntc_private.c
event.c
valve.c
electrode.c
temperature_controller.c
motor_server.c
dac121s101.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
