from building import *

cwd = GetCurrentDir()

CPPPATH = [cwd]
# add the general drivers.
src = Split("""
""")

if GetDepend(['BSP_USING_EXTERNED_ADC']):
    src += ['exadc_driver.c']
if GetDepend(['BSP_USING_CS1237']):
    src += ['cs1237.c']


path =  [cwd]
path += [cwd + '/config']

group = DefineGroup('ExternDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
